browser:
  browser_name: chrome
  headless: true
  attach_screenshot: true
  web_element_timeout: 10
environment:
  test_int:
    env_name: test_init
    app_url: http://146.59.32.4/
    cart_url: http://146.59.32.4/?controller=cart&action=show
    title: TesterSii
    user_gender: male
    user_first_name: Daniel
    user_last_name: Okniński
    user_email: danokn1991@gmail.com
    user_password: zaq123
    user_address: Polna 11
    user_country: United States
    user_city: Warszawa
    user_post_code: New York 12345
    user_street: Polna11
    currency: $
    active: true
  test:
    env_name: test
    app_url: https://logback.qos.ch/
    title: Logback Home
    active: false